INSERT INTO tasks (title, description, due_date, status) VALUES ('Fix mobile layout issues', 'Create a responsive and intuitive user dashboard layout.', '2025-05-31', 'IN_PROGRESS'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Fix mobile layout issues', 'Resolve issues causing login failure under certain edge cases.', '2025-05-23', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Design user dashboard', 'Fix layout shifting on smaller screens and iOS devices.', '2025-06-09', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Handle edge case errors', 'Compress and lazy-load high-resolution images.', '2025-06-10', 'COMPLETED'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Update user profile UI', 'Ensure at least 80% code coverage with meaningful unit tests.', '2025-05-22', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Write unit tests', 'Build a secure flow for users to reset forgotten passwords.', '2025-05-29', 'COMPLETED'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Update third-party libraries', 'Perform internal audit and address critical security gaps.', '2025-06-01', 'COMPLETED'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Run security audit', 'Catch and handle corner cases leading to crashes.', '2025-05-21', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Setup CI/CD pipeline', 'Add real-time task filtering based on status and due date.', '2025-05-27', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Deploy staging build', 'Resolve issues causing login failure under certain edge cases.', '2025-06-08', 'COMPLETED'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Document API endpoints', 'Investigate latest tech trends for possible integration.', '2025-05-23', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Create user onboarding flow', 'Ensure at least 80% code coverage with meaningful unit tests.', '2025-06-03', 'COMPLETED'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Handle edge case errors', 'Replace deprecated libraries with actively maintained ones.', '2025-05-29', 'COMPLETED'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Test email notifications', 'Implement GitHub Actions for automatic test and deploy.', '2025-05-21', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Review code for release', 'Fix layout shifting on smaller screens and iOS devices.', '2025-06-06', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Update third-party libraries', 'Create Postman collection with all updated endpoints.', '2025-05-16', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Deploy staging build', 'Create Postman collection with all updated endpoints.', '2025-05-15', 'IN_PROGRESS'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Update user profile UI', 'Investigate latest tech trends for possible integration.', '2025-05-29', 'IN_PROGRESS'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Deploy staging build', 'Add real-time task filtering based on status and due date.', '2025-05-19', 'COMPLETED'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Setup CI/CD pipeline', 'Resolve issues causing login failure under certain edge cases.', '2025-05-20', 'IN_PROGRESS'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Write unit tests', 'Build a secure flow for users to reset forgotten passwords.', '2025-05-31', 'IN_PROGRESS'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Update third-party libraries', 'Ensure consistent timestamps across all time zones.', '2025-06-08', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Fix login bug', 'Investigate latest tech trends for possible integration.', '2025-06-07', 'IN_PROGRESS'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Document API endpoints', 'Ensure consistent timestamps across all time zones.', '2025-06-03', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Deploy staging build', 'Conduct thorough code review before the next release push.', '2025-05-23', 'IN_PROGRESS'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Review code for release', 'Allow users to switch between different languages easily.', '2025-05-17', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Migrate database schema', 'Integrate application-level and server-level logging.', '2025-06-06', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Prepare sprint demo', 'Ensure up-to-date and clean technical documentation.', '2025-05-19', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Document API endpoints', 'Resolve issues causing login failure under certain edge cases.', '2025-06-05', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Research new tech stack', 'Create presentation for upcoming sprint showcase.', '2025-06-09', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Fix timezone issues', 'Create presentation for upcoming sprint showcase.', '2025-05-30', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Deploy staging build', 'Transition to a new normalized schema without data loss.', '2025-05-20', 'IN_PROGRESS'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Set up logging', 'Investigate latest tech trends for possible integration.', '2025-05-14', 'COMPLETED'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Add task filtering', 'Add real-time task filtering based on status and due date.', '2025-05-13', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Handle edge case errors', 'Build a secure flow for users to reset forgotten passwords.', '2025-05-13', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Deploy staging build', 'Perform internal audit and address critical security gaps.', '2025-05-18', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Implement dark mode', 'Send alerts to Slack for specific app events.', '2025-06-03', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Create user onboarding flow', 'Conduct thorough code review before the next release push.', '2025-05-27', 'IN_PROGRESS'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Implement dark mode', 'Replace deprecated libraries with actively maintained ones.', '2025-06-10', 'IN_PROGRESS'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Create user onboarding flow', 'Refactor and modularize existing RESTful APIs for scalability.', '2025-05-14', 'IN_PROGRESS'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Research new tech stack', 'Ensure consistent timestamps across all time zones.', '2025-05-13', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Optimize image loading', 'Deploy latest features and patches to staging environment.', '2025-06-07', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Refactor backend APIs', 'Ensure consistent timestamps across all time zones.', '2025-05-17', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Handle edge case errors', 'Catch and handle corner cases leading to crashes.', '2025-05-24', 'COMPLETED'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Optimize image loading', 'Create a responsive and intuitive user dashboard layout.', '2025-06-03', 'IN_PROGRESS'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Update user profile UI', 'Ensure up-to-date and clean technical documentation.', '2025-06-08', 'IN_PROGRESS'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Handle edge case errors', 'Conduct thorough code review before the next release push.', '2025-05-23', 'IN_PROGRESS'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Update documentation', 'Ensure consistent timestamps across all time zones.', '2025-06-03', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Migrate database schema', 'Catch and handle corner cases leading to crashes.', '2025-06-12', 'COMPLETED'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Run security audit', 'Allow users to switch between different languages easily.', '2025-05-28', 'COMPLETED'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Migrate database schema', 'Perform internal audit and address critical security gaps.', '2025-06-01', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Fix login bug', 'Refactor and modularize existing RESTful APIs for scalability.', '2025-06-08', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Research new tech stack', 'Analyze and optimize queries slowing down task retrieval.', '2025-05-25', 'COMPLETED'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Review code for release', 'Identify and remove unused legacy functions in codebase.', '2025-05-20', 'COMPLETED'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Run security audit', 'Replace deprecated libraries with actively maintained ones.', '2025-05-23', 'IN_PROGRESS'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Update third-party libraries', 'Send alerts to Slack for specific app events.', '2025-05-29', 'COMPLETED'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Clean up legacy code', 'Create Postman collection with all updated endpoints.', '2025-06-11', 'IN_PROGRESS'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Enable multi-language support', 'Integrate application-level and server-level logging.', '2025-05-23', 'IN_PROGRESS'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Review performance metrics', 'Implement GitHub Actions for automatic test and deploy.', '2025-06-12', 'IN_PROGRESS'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Write unit tests', 'Build a secure flow for users to reset forgotten passwords.', '2025-06-08', 'IN_PROGRESS'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Review code for release', 'Integrate application-level and server-level logging.', '2025-05-23', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Fix login bug', 'Create Postman collection with all updated endpoints.', '2025-06-07', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Optimize image loading', 'Ensure consistent timestamps across all time zones.', '2025-05-19', 'IN_PROGRESS'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Deploy staging build', 'Create a responsive and intuitive user dashboard layout.', '2025-06-09', 'COMPLETED'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Setup CI/CD pipeline', 'Conduct thorough code review before the next release push.', '2025-06-11', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Enable multi-language support', 'Transition to a new normalized schema without data loss.', '2025-06-10', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Set up logging', 'Analyze response times and eliminate bottlenecks.', '2025-05-27', 'IN_PROGRESS'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Set up logging', 'Implement GitHub Actions for automatic test and deploy.', '2025-05-21', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Optimize database queries', 'Replace deprecated libraries with actively maintained ones.', '2025-05-13', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Migrate database schema', 'Deploy latest features and patches to staging environment.', '2025-05-22', 'COMPLETED'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Review code for release', 'Ensure at least 80% code coverage with meaningful unit tests.', '2025-05-31', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Fix timezone issues', 'Deploy latest features and patches to staging environment.', '2025-06-10', 'IN_PROGRESS'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Test email notifications', 'Identify and remove unused legacy functions in codebase.', '2025-06-08', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Integrate with Slack', 'Conduct thorough code review before the next release push.', '2025-05-30', 'COMPLETED'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Write unit tests', 'Create a responsive and intuitive user dashboard layout.', '2025-06-11', 'IN_PROGRESS'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Update user profile UI', 'Send alerts to Slack for specific app events.', '2025-05-22', 'COMPLETED'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Design user dashboard', 'Allow users to switch between different languages easily.', '2025-05-30', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Add task filtering', 'Investigate latest tech trends for possible integration.', '2025-05-23', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Update user profile UI', 'Send alerts to Slack for specific app events.', '2025-05-26', 'COMPLETED'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Implement password reset', 'Analyze and optimize queries slowing down task retrieval.', '2025-05-31', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Optimize database queries', 'Allow users to switch between different languages easily.', '2025-05-20', 'IN_PROGRESS'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Update third-party libraries', 'Catch and handle corner cases leading to crashes.', '2025-06-02', 'COMPLETED'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Review performance metrics', 'Redesign user profile page with updated frontend components.', '2025-05-25', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Prepare sprint demo', 'Implement GitHub Actions for automatic test and deploy.', '2025-05-26', 'COMPLETED'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Migrate database schema', 'Send alerts to Slack for specific app events.', '2025-05-19', 'COMPLETED'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Research new tech stack', 'Redesign user profile page with updated frontend components.', '2025-05-20', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Integrate with Slack', 'Fix layout shifting on smaller screens and iOS devices.', '2025-05-30', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Enable multi-language support', 'Investigate latest tech trends for possible integration.', '2025-06-08', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Run security audit', 'Perform internal audit and address critical security gaps.', '2025-06-07', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Enable multi-language support', 'Resolve issues causing login failure under certain edge cases.', '2025-05-17', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Design user dashboard', 'Refactor and modularize existing RESTful APIs for scalability.', '2025-05-16', 'IN_PROGRESS'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Deploy staging build', 'Analyze response times and eliminate bottlenecks.', '2025-05-25', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Setup CI/CD pipeline', 'Replace deprecated libraries with actively maintained ones.', '2025-05-21', 'COMPLETED'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Update documentation', 'Integrate application-level and server-level logging.', '2025-06-08', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Migrate database schema', 'Replace deprecated libraries with actively maintained ones.', '2025-05-30', 'IN_PROGRESS'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Add task filtering', 'Analyze response times and eliminate bottlenecks.', '2025-05-20', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Handle edge case errors', 'Refactor and modularize existing RESTful APIs for scalability.', '2025-06-06', 'COMPLETED'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Run security audit', 'Analyze and optimize queries slowing down task retrieval.', '2025-05-31', 'PENDING'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Fix login bug', 'Resolve issues causing login failure under certain edge cases.', '2025-06-05', 'COMPLETED'::task_status);
INSERT INTO tasks (title, description, due_date, status) VALUES ('Optimize database queries', 'Compress and lazy-load high-resolution images.', '2025-06-05', 'COMPLETED'::task_status);